FROM node:22-alpine

WORKDIR /app

# Enable pnpm 
RUN corepack enable


COPY package.json pnpm-lock.yaml* ./

# Install dependencies
RUN pnpm install --frozen-lockfile || pnpm install

COPY . .

ENV NODE_ENV=development

EXPOSE 3000

CMD sh -c "npx prisma generate && pnpm run start:dev"
